/*
public class exception {
    public static void main(String[] args){
        try  
        {  
            int data=50/0; 
        }       
        catch(Exception e)  
        {  
            System.out.println(e);  
        }  
        System.out.println("Completed");
    }
}*/
/*
public class exception {
    public static void main(String[] args) {  
        try  
        {  
        int arr[]= {1,3,5,7};  
        System.out.println(arr[10]);  
        }   
        catch(ArrayIndexOutOfBoundsException e)  
        {  
            System.out.println(e);  
        }  
        System.out.println("Completed");  
    } 
}*/
/*
public class exception {
    public static void main(String[] args) {  
        PrintWriter pw;  
        try {  
            pw = new PrintWriter("jtp.txt"); //may throw exception   
            pw.println("saved");  
        }   
        catch (FileNotFoundException e) {
            System.out.println("File not found!");  
        }         
        System.out.println("File saved successfully");  
    } 
}*/
/*
public class exception {
    public static void main(String[] args) {  
        try  
        {  
            int data1=50/0;   
  
        }
        catch(Exception e)  
        {  
            int data2=50/0;
  
        }  
    System.out.println("@ try");    
    } 
}*/